### ISSUE TITLE
Re-review for hateoas guide

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/guide-rest-hateoas#22]
See https://github.com/OpenLiberty/guide-rest-hateoas/pull/21

**bugs/general**
- [x] the `*` hostname, which is used to list all hosts in the inventory, has a `properties` link attached to its `_links` array. This is incorrect, this hostname is a special case but it wasn't treated as such.
- [x] I think it would be better to use the `<rel>:<href>` format for hypermedia links than what we currently have. It will be much easier to access links this way. In other words, its probably much easier to just have a call `<some object>.get('relationship')` rather than looping through an array of links and checking each one for the relationship we need.
- [x] rename `ReadyJson`
- [x] I really dislike that fact that we deviated from using future tense (ie. words like "will"). I felt like it tied the sections much better together and allowed the guide to flow more naturally. The users have obviously not implemented various methods and classes, so in my opinion its much better to say what the method they will implement **will** do rather what it **is** doing.
- [x] I also don't like the use of "lets" throughout the guide; ie. "Let's implement this method...". We've deviated from using "we" and using "lets" its kind of similar in that regard

**What you'll learn**
- [x] this whole section needs rewording as its very confusing + has the same issue that one user experienced with the MP guide
- [x] the "Response JSON" section is way too long. I dont think we need to go into too much detail here. Just talking about how hypermedia links will be styled and what the `_links` array is for should be enough.

**Other sections**
- [x] same issues with only using present tense: sentences dont flow at all and a lot of them seem very awkward.

**Testing**
- [ ] testing section still refers to the `/hosts` endpoint as the contents of the inventory, which is no longer valid since its now hypermedia-driven
- [x] testing section assumes that the `inventory` and `system` services are running on separate servers, which is incorrect
- [x] I think its redundant to keep mentioning how the inventory and system services talk to each, we should consider removing that explanation from the starting paragraph
- [x] I dont think we need to explain what the test suite does, it takes away from the overall guide. Saying something like "place all your test cases into a single container method" should be enough
- [x] "This technique" -> this just sounds cheesy, using helper method is a technique, but the word "technique" is only used to teach first year cs students
- [x] replace "mvn clean install" with "mvn verify"

This is just an idea, but perhaps we could change each testing section to be "Testing what you built" rather than being guide specific?

One thing to note though is that we have to keep the `start` directory synced up with the MP guide's `finish` directory. If we make any changes to the starting code that is.

**Comment by TiagoF99** [comment]
In progress

**Comment by TiagoF99** [comment]
> This is just an idea, but perhaps we could change each testing section to be "Testing what you built" rather than being guide specific?
- Will research this

**Comment by TiagoF99** [comment]
addressed with PR https://github.com/OpenLiberty/guide-rest-hateoas/pull/70

**Comment by griffinhadfield** [comment]
In the first modification of the guide, the user is asked to replace the `InventoryResoure.java` class. The guide then states that
```
The contents of your inventory are now under the asterisk (*) wildcard and reside at the following URL: http://localhost:9080/inventory/hosts/*
```

However in this new class, the `InventoryManager` `getSystems()` method is used, however this method does not get implemented until the next file modification. At this point the source compilation fails, and thus the link above does not actually work yet.

I think the guide needs to be modified so that either the `getSystems()` method is implemented first, or so that the guide doesn't claim that URL will work after the first modification. 

Everything else works from what I can see.

**Comment by AustinSeto** [comment]
Taking over this issue for Tiago
