### ISSUE TITLE
multipane issues

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-rest-hateoas#40]
- [x] no git clone command on the right pane
- [x] the URL "Creating a MicroProfile application" point to CDI guide, it should be incorrect.
- [x] instruction does not ask reader to navigate to start directory to start
- [x] Create the InventoryResource class but InventoryResource already exist in the start directory. The original guide does not ask to create. So the multipane should ask to read it
- [x] `http://localhost:9080/inventory/hosts/<hostname>;` should remove the semi-colon. If possible, treat it as an non URL link 
- [ ] at the "Testing the hypermedia-driven RESTful web service" section, suggest to add http://localhost:9080/inventory/hosts/localhost
- [x] the hotspot GET in the following should highlight the `Response targetResponse...` instead of `targetResponse.close();`
   - Finally, the method visitLocalhost creates a GET request to the system service, registering the localhost system.
- [x] Rewrite the "Running the tests" section, so that to run `mvn liberty:stop-server` first then run `mvn install` 
- [ ] the test failed

**Comment by justineechen** [comment]
- The link `https://openliberty.io/guides/microprofile-intro.html` that this guide points to doesn't exist anymore. I will remove this sentence. 

-Do we want to replace `http://localhost:9080/inventory/hosts/{hostname}[http://localhost:9080/inventory/hosts/{hostname}^]` and give the users localhost directly for the link in Testing?

**Comment by evelinec** [comment]
Found the fixed the code_command for "InventoryUtil" isn't pointing to the correct file issue in https://github.com/OpenLiberty/guide-rest-hateoas/commit/bb6436f85379aa529fad8cbfadc7ed31e6c05432.

**Comment by evelinec** [comment]
Test had passed when I tried it today.

**Comment by evelinec** [comment]
Verified all the points in the description of this issue, except for this one: 

* at the "Testing the hypermedia-driven RESTful web service" section, suggest to add http://localhost:9080/inventory/hosts/localhost

Not sure that's needed.

**Comment by evelinec** [comment]
@gkwan-ibm Do you want to take a quick look to see if everything is ok to close this issue? Thanks.

**Comment by gkwan-ibm** [comment]
> Verified all the points in the description of this issue, except for this one:
> 
>     * at the "Testing the hypermedia-driven RESTful web service" section, suggest to add http://localhost:9080/inventory/hosts/localhost
> 
> 
> Not sure that's needed.

That should be resolved

**Comment by evelinec** [comment]
> > Verified all the points in the description of this issue, except for this one:
> > ```
> > * at the "Testing the hypermedia-driven RESTful web service" section, suggest to add http://localhost:9080/inventory/hosts/localhost
> > ```
> > Not sure that's needed.
> 
> That should be resolved

@gkwan-ibm can you be a little be more specific? Do you think the `localhost` url should be added as an additional bullet at the beginning of this section? What do you think is the purpose? If we do add this url, we need to explain it in the paragraph below.
